import {
  Customer,
  Device,
  ServiceOrder,
  Product,
  Sale,
  CashSession,
  Expense,
  Employee,
  AccountReceivable,
  CompanySettings,
  AuditLog,
  StockMovement,
  Purchase,
  Reseller,
  ResellerTransaction,
} from '../types';

export const initialCompanySettings: CompanySettings = {
  name: 'TECHNOVA INFORMÁTICA & CELULARES',
  commercialName: 'TECHNOVA ASSISTÊNCIA TÉCNICA',
  ownerName: 'Carlos Eduardo Silva',
  slogan: 'SOLUÇÕES INTELIGENTES EM TECNOLOGIA',
  cnpj: '12.345.678/0001-90',
  cnpjCpf: '12.345.678/0001-90',
  address: 'Av. Paulista, 1000 - Loja 12',
  neighborhood: 'Bela Vista',
  city: 'São Paulo',
  state: 'SP',
  zipCode: '01310-100',
  phone: '(11) 98765-4321',
  whatsapp: '(11) 98765-4321',
  email: 'contato@technovasp.com.br',
  instagram: '@technova.assistencia',
  logoUrl: '',
  warrantyText: 'Garantia legal de 90 dias sobre serviços e peças\nGuarde essa OS ela é a sua garantia do serviço\nA Garantia não cobre mau uso ou contato com líquidos',
  defaultWarrantyTerms: 'Garantia legal de 90 dias sobre serviços e peças\nGuarde essa OS ela é a sua garantia do serviço\nA Garantia não cobre mau uso ou contato com líquidos',
  receiptDisclaimer: 'Garantia legal de 90 dias sobre serviços e peças\nGuarde essa OS ela é a sua garantia do serviço\nA Garantia não cobre mau uso ou contato com líquidos',
  defaultWarrantyDays: 90,
  requireOpenCashForSales: true,
  printHeaderNote: 'SOLUÇÕES INTELIGENTES EM TECNOLOGIA',
  printFooterNote: 'Guarde essa OS ela é a sua garantia do serviço. A Garantia não cobre mau uso',
  saasReady: true,
  managerPassword: '1507',

  // OS Thermal Print customizations based on thermal ticket format
  osReceiptTitle: 'Ordem Servico',
  osReceiptSubtitle: 'Comprovante de Recebimento',
  osChecklistText: '',
  osResponsibleSignLabel: 'Ass. do Responsável',
  osCustomerSignLabel: 'Ass. do Cliente',
  osFooterTerms: 'Garantia legal de 90 dias sobre serviços e peças\nGuarde essa OS ela é a sua garantia do serviço\nA Garantia não cobre mau uso ou contato com líquidos',
  osShowProblemBox: true,
  osShowLaudoBox: true,
  osShowNotesBox: true,
  osShowSignatures: false,
  osShowCustomerAddress: true,
  osDefaultPaperFormat: '80mm',
};

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Administrador da Assistência',
    cpf: '123.456.789-00',
    phone: '(11) 98111-2233',
    email: 'admin@assistencia.com.br',
    role: 'ADMINISTRADOR',
    username: 'admin',
    status: 'ATIVO',
    permissions: {
      canAccessAdminSettings: true,
      canViewFinancialReports: true,
      canViewProductCost: true,
      canManageEmployees: true,
      canManageProducts: true,
      canManageCustomers: true,
      canManageOrders: true,
      canOperatePos: true,
      canOperateCash: true,
      canManageExpenses: true,
      canDeleteRecords: true,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T08:00:00.000Z',
  },
  {
    id: 'emp-2',
    name: 'Rafael Oliveira (Técnico Chefe)',
    cpf: '234.567.890-11',
    phone: '(11) 97222-3344',
    email: 'rafael@mspinformatica.com.br',
    role: 'TECNICO',
    username: 'rafael',
    status: 'ATIVO',
    permissions: {
      canAccessAdminSettings: false,
      canViewFinancialReports: false,
      canViewProductCost: false,
      canManageEmployees: false,
      canManageProducts: false,
      canManageCustomers: true,
      canManageOrders: true,
      canOperatePos: false,
      canOperateCash: false,
      canManageExpenses: false,
      canDeleteRecords: false,
    },
    createdAt: '2025-01-15T09:00:00.000Z',
  },
  {
    id: 'emp-3',
    name: 'Juliana Costa (Vendedora / Caixa)',
    cpf: '345.678.901-22',
    phone: '(11) 99333-4455',
    email: 'juliana@mspinformatica.com.br',
    role: 'VENDEDOR',
    username: 'juliana',
    status: 'ATIVO',
    permissions: {
      canAccessAdminSettings: false,
      canViewFinancialReports: false,
      canViewProductCost: false,
      canManageEmployees: false,
      canManageProducts: false,
      canManageCustomers: true,
      canManageOrders: true,
      canOperatePos: true,
      canOperateCash: true,
      canManageExpenses: true,
      canDeleteRecords: false,
    },
    createdAt: '2025-02-01T08:30:00.000Z',
  },
  {
    id: 'emp-4',
    name: 'Carlos Mendes (Gerente)',
    cpf: '456.789.012-33',
    phone: '(11) 98444-5566',
    email: 'carlos@mspinformatica.com.br',
    role: 'GERENTE',
    username: 'carlos',
    status: 'ATIVO',
    permissions: {
      canAccessAdminSettings: true,
      canViewFinancialReports: true,
      canViewProductCost: true,
      canManageEmployees: false,
      canManageProducts: true,
      canManageCustomers: true,
      canManageOrders: true,
      canOperatePos: true,
      canOperateCash: true,
      canManageExpenses: true,
      canDeleteRecords: false,
    },
    createdAt: '2025-01-20T10:00:00.000Z',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Carlos Eduardo Santos',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    document: '345.678.912-00',
    email: 'carlos.eduardo@email.com',
    address: 'Av. Paulista, 1000 - Bela Vista',
    city: 'São Paulo - SP',
    debtBalance: 0,
    createdAt: '2025-01-20T10:00:00.000Z',
  },
];

export const initialDevices: Device[] = [
  {
    id: 'dev-1',
    customerId: 'cust-1',
    customerName: 'Carlos Eduardo Santos',
    type: 'Smartphone',
    brand: 'Samsung',
    model: 'Galaxy A54 5G',
    serialNumber: 'R58M90ABCDE',
    imei: '358742091234567',
    color: 'Preto',
    physicalCondition: 'Pequenos riscos de uso na tampa traseira',
    accessoriesDelivered: 'Capa Protetora Transparente',
    notes: 'Aparelho bem conservado',
    createdAt: '2025-01-20T10:00:00.000Z',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Subplaca Conector Carga Samsung A54',
    sku: 'PEC-SAM-A54-SUB',
    barcode: '7891000200030',
    category: 'Peças',
    costPrice: 35.0,
    sellingPrice: 80.0,
    resellerPrice: 65.0,
    stockQuantity: 10,
    minStockQuantity: 2,
    brand: 'Samsung',
    model: 'Galaxy A54',
    unit: 'UN',
    isActive: true,
    createdAt: '2025-01-20T10:00:00.000Z',
  },
];

export const initialOrders: ServiceOrder[] = [
  {
    id: 'os-1001',
    orderNumber: 1001,
    customerId: 'cust-1',
    customerName: 'Carlos Eduardo Santos',
    customerPhone: '(11) 98765-4321',
    customerWhatsapp: '(11) 98765-4321',
    customerDocument: '345.678.912-00',
    deviceId: 'dev-1',
    deviceType: 'Smartphone',
    brand: 'Samsung',
    model: 'Galaxy A54 5G',
    imei: '358742091234567',
    serialNumber: 'R58M90ABCDE',
    passwordPin: '1234',
    passwordType: 'PIN',
    accessories: 'Capa Protetora Transparente',
    physicalCondition: 'Pequenos riscos na tampa traseira, sem trincos',
    physicalState: 'Pequenos riscos na tampa traseira, sem trincos',
    clientDefect: 'Aparelho não carrega e conector esquenta ao plugar no carregador',
    technicalDiagnosis: 'Conector de carga tipo C oxidado com curto na placa sub',
    requestedService: 'Troca da placa do conector de carga (Subplaca) e limpeza interna',
    performedService: 'Troca da placa do conector de carga (Subplaca) e limpeza interna',
    laborPrice: 120,
    partsPrice: 80,
    discount: 0,
    totalPrice: 200,
    paymentMethod: 'PIX',
    paymentStatus: 'PENDENTE',
    status: 'ORCAMENTO',
    archivedLocation: 'Gaveta 1',
    technicianName: 'Juliana Costa',
    attendantName: 'Juliana Costa',
    warrantyDays: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: 'part-ex-1',
        name: 'Subplaca Conector Carga Samsung A54',
        productName: 'Subplaca Conector Carga Samsung A54',
        type: 'PECA',
        quantity: 1,
        unitPrice: 80,
        discount: 0,
        total: 80,
        totalPrice: 80,
      },
    ],
    parts: [
      {
        id: 'part-ex-1',
        name: 'Subplaca Conector Carga Samsung A54',
        productName: 'Subplaca Conector Carga Samsung A54',
        type: 'PECA',
        quantity: 1,
        unitPrice: 80,
        discount: 0,
        total: 80,
        totalPrice: 80,
      },
    ],
    statusHistory: [
      {
        status: 'ORCAMENTO',
        changedAt: new Date().toISOString(),
        changedBy: 'Juliana Costa',
        notes: 'Ordem de serviço criada com diagnóstico inicial.',
      },
    ],
    history: [
      {
        status: 'ORCAMENTO',
        changedAt: new Date().toISOString(),
        changedBy: 'Juliana Costa',
        notes: 'Ordem de serviço criada com diagnóstico inicial.',
      },
    ],
  },
];
export const initialSales: Sale[] = [];

export const initialCashSession: CashSession = {
  id: 'cash-sess-active',
  openedAt: new Date().toISOString(),
  openedBy: 'Super Admin',
  openingBalance: 0,
  initialBalance: 0,
  currentBalance: 0,
  status: 'ABERTO',
  notes: 'Caixa inicial',
  movements: [],
};

export const initialExpenses: Expense[] = [];
export const initialStockMovements: StockMovement[] = [];
export const initialPurchases: Purchase[] = [];
export const initialReceivables: AccountReceivable[] = [];
export const initialResellers: Reseller[] = [];
export const initialResellerTransactions: ResellerTransaction[] = [];
export const initialAuditLogs: AuditLog[] = [];
